security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: CODEUTIL

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: codeutil
                password_parameter: password
                default_target_path: app_produit_index

            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

            entry_point: form_login

    access_control:
        - { path: ^/produit, roles: PUBLIC_ACCESS  }
        - { path: ^/login, roles: PUBLIC_ACCESS  }
        - { path: ^/utilisateur, roles: PUBLIC_ACCESS  }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext
                cost: 4
                time_cost: 3
                memory_cost: 10
